/*
 This file is auto generated by GTT module.
 DO NOT MODIFY EXPORTED INTERFACE IN THIS FILE. 
*/

enum PaymentMethods {
	CB = 'cb',
	GIFT_CARD = 'gift_card',
	CASH = 'cash',
}
enum Roles {
	CHEF_COOK = 'chef_cook',
	GENERAL_MANAGER = 'general_manager',
	OWNER = 'owner',
	SERVER = 'server',
}
enum ProductType {
	CLOTH = 'cloth',
	FOOD = 'food',
	TOY = 'toy',
}
