/*
 This file is auto generated by GTT module.
 DO NOT MODIFY EXPORTED INTERFACE IN THIS FILE. 
*/

declare namespace product {
	export interface Item {
		name : string;
		price : number;
		in_stock : boolean;
	}

}


declare namespace newcontext {
	export interface Address {
		id : number;
		street : string;
		h_number : string;
		city : string;
		country_code : string;
	}

}


