/*
 This file is auto generated by GTT module.
 DO NOT MODIFY EXPORTED INTERFACE IN THIS FILE. 
*/

export interface Address {
	id : number;
	street : string;
	h_number : string;
	city : string;
	country_code : string;
}

