/*
 This file is auto generated by GTT module.
 DO NOT MODIFY EXPORTED INTERFACE IN THIS FILE. 
*/

export interface User {
	person : Person;
	pwd : string;
	login : string;
}

export interface Person {
	name : string;
	given : string;
	gender : string;
	phone ?: string;
	email : string;
}

