// Code generated by "stringer -type=paymentMethods,roles -output=stringEnumsMethods.go"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CB-0]
	_ = x[CASH-1]
	_ = x[GIFT_CARD-2]
}

const _paymentMethods_name = "CBCASHGIFT_CARD"

var _paymentMethods_index = [...]uint8{0, 2, 6, 15}

func (i paymentMethods) String() string {
	if i < 0 || i >= paymentMethods(len(_paymentMethods_index)-1) {
		return "paymentMethods(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _paymentMethods_name[_paymentMethods_index[i]:_paymentMethods_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OWNER-3]
	_ = x[GENERAL_MANAGER-4]
	_ = x[CHEF_COOK-5]
	_ = x[SERVER-6]
}

const _roles_name = "OWNERGENERAL_MANAGERCHEF_COOKSERVER"

var _roles_index = [...]uint8{0, 5, 20, 29, 35}

func (i roles) String() string {
	i -= 3
	if i < 0 || i >= roles(len(_roles_index)-1) {
		return "roles(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _roles_name[_roles_index[i]:_roles_index[i+1]]
}
