// Code generated by "stringer -type=productType -output=stringEnumsMethods.go"; DO NOT EDIT.

package productDomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOY-0]
	_ = x[FOOD-1]
	_ = x[CLOTH-2]
}

const _productType_name = "TOYFOODCLOTH"

var _productType_index = [...]uint8{0, 3, 7, 12}

func (i productType) String() string {
	if i < 0 || i >= productType(len(_productType_index)-1) {
		return "productType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _productType_name[_productType_index[i]:_productType_index[i+1]]
}
